name: Generate Posts & Sitemaps

on:
  push:
    branches:
      - main 
    paths:
      - 'encyclopedia.docx' 
      - 'scripts/**'       
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Force cleanup of old generated files
        run: |
          # تنظيف الملفات المولدة سابقاً قبل البدء
          rm -rf posts/
          rm -f sitemap_*.xml sitemap_index.xml
          rm -f index.json 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-docx python-slugify

      - name: Extract, Generate Sitemaps, and Commit Changes
        run: |
          echo "Starting extraction and sitemap generation..."

          # 1. تشغيل سكربت استخراج المقالات
          python scripts/extract_articles.py

          # 2. تشغيل سكربت توليد خرائط الموقع (والفهرس JSON)
          python scripts/generate_sitemaps.py
          
          # 3. إعداد Git للمزامنة والإرسال
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          
          # إضافة جميع الملفات المولدة حديثاً (المجلد، خرائط الموقع، ملف الفهرس)
          git add posts/
          git add sitemap_*.xml
          git add sitemap_index.xml
          git add index.json  # <--- تأكدنا من وجود هذا السطر 
          
          # 4. التحقق من وجود تغييرات لـ Commit (لتجنب Push فارغ)
          if git status --porcelain | grep -q .; then
            echo "Changes detected. Committing and pushing..."
            git commit -m "Auto-generate posts, sitemaps, and index.json"
            git push
          else
            echo "No new changes. Skipping commit."
          fi
